# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RemoteFileReader.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RemoteFileReader.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16RemoteFileReader.proto\"\x18\n\x08\x46ileLine\x12\x0c\n\x04line\x18\x01 \x01(\t\"S\n\nFileStatus\x12\x13\n\x0b\x66ile_exists\x18\x01 \x01(\x08\x12\x14\n\x0c\x63reated_time\x18\x02 \x01(\t\x12\x1a\n\x12last_modified_date\x18\x03 \x01(\t\"\x18\n\x04\x46ile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t2X\n\x18RemoteFileRreaderService\x12\x1e\n\x06\x65xists\x12\x05.File\x1a\x0b.FileStatus\"\x00\x12\x1c\n\x04read\x12\x05.File\x1a\t.FileLine\"\x00\x30\x01\x62\x06proto3')
)




_FILELINE = _descriptor.Descriptor(
  name='FileLine',
  full_name='FileLine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line', full_name='FileLine.line', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=50,
)


_FILESTATUS = _descriptor.Descriptor(
  name='FileStatus',
  full_name='FileStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_exists', full_name='FileStatus.file_exists', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_time', full_name='FileStatus.created_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_modified_date', full_name='FileStatus.last_modified_date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=135,
)


_FILE = _descriptor.Descriptor(
  name='File',
  full_name='File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='File.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['FileLine'] = _FILELINE
DESCRIPTOR.message_types_by_name['FileStatus'] = _FILESTATUS
DESCRIPTOR.message_types_by_name['File'] = _FILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileLine = _reflection.GeneratedProtocolMessageType('FileLine', (_message.Message,), dict(
  DESCRIPTOR = _FILELINE,
  __module__ = 'RemoteFileReader_pb2'
  # @@protoc_insertion_point(class_scope:FileLine)
  ))
_sym_db.RegisterMessage(FileLine)

FileStatus = _reflection.GeneratedProtocolMessageType('FileStatus', (_message.Message,), dict(
  DESCRIPTOR = _FILESTATUS,
  __module__ = 'RemoteFileReader_pb2'
  # @@protoc_insertion_point(class_scope:FileStatus)
  ))
_sym_db.RegisterMessage(FileStatus)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(
  DESCRIPTOR = _FILE,
  __module__ = 'RemoteFileReader_pb2'
  # @@protoc_insertion_point(class_scope:File)
  ))
_sym_db.RegisterMessage(File)



_REMOTEFILERREADERSERVICE = _descriptor.ServiceDescriptor(
  name='RemoteFileRreaderService',
  full_name='RemoteFileRreaderService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=163,
  serialized_end=251,
  methods=[
  _descriptor.MethodDescriptor(
    name='exists',
    full_name='RemoteFileRreaderService.exists',
    index=0,
    containing_service=None,
    input_type=_FILE,
    output_type=_FILESTATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='read',
    full_name='RemoteFileRreaderService.read',
    index=1,
    containing_service=None,
    input_type=_FILE,
    output_type=_FILELINE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOTEFILERREADERSERVICE)

DESCRIPTOR.services_by_name['RemoteFileRreaderService'] = _REMOTEFILERREADERSERVICE

# @@protoc_insertion_point(module_scope)
